In [2]:
import requests
from bs4 import BeautifulSoup

In [3]:
web = requests.get("https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops")
web

In [4]:
soup = BeautifulSoup(web.content, "html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="gXifVBy7T72zBny9XZ5v9jnli1JxmLff">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=f90c5791d7eb09506961d9ee889840b2" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$321.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">5</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$356.49</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">6</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$364.46</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
						Hewlett Packar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$372.7</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
						Acer Aspire 3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
						Acer Aspire A3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">0</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.95</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
						Acer Aspire ES...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">9</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$391.48</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [5]:
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="gXifVBy7T72zBny9XZ5v9jnli1JxmLff">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Allinone | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=f90c5791d7eb09506961d9ee889840b2" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>\n    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $295.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">\n             Asus VivoBook...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             14\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $321.94\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             5\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $356.49\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             6\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $364.46\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/65" 

In [14]:
names = soup.find_all("a", class_ = "title")
na = []
for name in names:
  print(name.text.strip())
  na.append(name.text.strip())

Asus VivoBook...
Prestigio Smar...
Prestigio Smar...
Aspire E1-510
Lenovo V110-15...
Lenovo V110-15...
Hewlett Packar...
Acer Aspire 3...
Acer Aspire A3...
Acer Aspire ES...
Acer Aspire 3...
Acer Aspire 3...
Asus VivoBook...
Asus VivoBook...
Lenovo ThinkPa...
Acer Aspire 3...
Lenovo V110-15...
Acer Aspire ES...
Asus VivoBook...
Packard 255 G2
Asus EeeBook R...
Acer Aspire 3...
Acer Aspire ES...
Acer Extensa 1...
Acer Aspire ES...
Lenovo V110-15...
Acer Aspire A3...
Lenovo V110-15...
Asus VivoBook...
Acer Aspire ES...
Lenovo V510 Bl...
Acer Aspire ES...
Lenovo V510 Bl...
Acer Swift 1 S...
Dell Vostro 15
Acer Aspire 3...
Dell Vostro 15...
Lenovo V510 Bl...
HP 250 G3
Acer Spin 5
HP 350 G1
Aspire E1-572G
Pavilion
Acer Aspire A5...
Dell Inspiron...
Asus VivoBook...
ProBook
Inspiron 15
Asus ROG STRIX...
Acer Nitro 5 A...
Asus ROG STRIX...
Lenovo ThinkPa...
ThinkPad Yoga
Lenovo ThinkPa...
Dell Inspiron...
MSI GL72M 7RDX
MSI GL72M 7RDX
Asus ROG Strix...
Dell Latitude...
Dell Latitude...
Lenovo Legion...
Toshiba Porteg...
Acer Predator...
Acer Aspire 7...
Dell Inspiron...
Dell Latitude...
Lenovo Legion...
Asus AsusPro A...
Acer Nitro 5 A...
Dell Latitude...
Dell Inspiron...
Dell Latitude...
Lenovo Legion...
MSI GP62M 7RDX...
Lenovo Yoga 72...
Toshiba Porteg...
Acer TravelMat...
Dell Latitude...
ThinkPad T540p
MSI GS63 7RD S...
Dell Latitude...
Acer Predator...
MSI GL62M 7REX
MSI GL62M 7REX...
Lenovo Yoga 91...
Toshiba Porteg...
Lenovo IdeaPad...
Acer Predator...
ThinkPad Yoga
Asus VivoBook...
Dell Latitude...
Asus ZenBook U...
ThinkPad X230
Asus ROG Strix...
Apple MacBook...
Dell Latitude...
Hewlett Packar...
Dell XPS 13
Toshiba Porteg...
MSI GL62VR 7RF...
Dell Latitude...
ThinkPad X240
Hewlett Packar...
Apple MacBook...
Dell Latitude...
Dell Latitude...
Dell Latitude...
Apple MacBook...
Lenovo ThinkPa...
Lenovo ThinkPa...
Toshiba Porteg...
Asus ASUSPRO B...
Lenovo Legion...
Asus ROG Strix...
Asus ROG Strix...
Asus ROG Strix...
Asus ROG Strix...

In [15]:
na

['Asus VivoBook...',
 'Prestigio Smar...',
 'Prestigio Smar...',
 'Aspire E1-510',
 'Lenovo V110-15...',
 'Lenovo V110-15...',
 'Hewlett Packar...',
 'Acer Aspire 3...',
 'Acer Aspire A3...',
 'Acer Aspire ES...',
 'Acer Aspire 3...',
 'Acer Aspire 3...',
 'Asus VivoBook...',
 'Asus VivoBook...',
 'Lenovo ThinkPa...',
 'Acer Aspire 3...',
 'Lenovo V110-15...',
 'Acer Aspire ES...',
 'Asus VivoBook...',
 'Packard 255 G2',
 'Asus EeeBook R...',
 'Acer Aspire 3...',
 'Acer Aspire ES...',
 'Acer Extensa 1...',
 'Acer Aspire ES...',
 'Lenovo V110-15...',
 'Acer Aspire A3...',
 'Lenovo V110-15...',
 'Asus VivoBook...',
 'Acer Aspire ES...',
 'Lenovo V510 Bl...',
 'Acer Aspire ES...',
 'Lenovo V510 Bl...',
 'Acer Swift 1 S...',
 'Dell Vostro 15',
 'Acer Aspire 3...',
 'Dell Vostro 15...',
 'Lenovo V510 Bl...',
 'HP 250 G3',
 'Acer Spin 5',
 'HP 350 G1',
 'Aspire E1-572G',
 'Pavilion',
 'Acer Aspire A5...',
 'Dell Inspiron...',
 'Asus VivoBook...',
 'ProBook',
 'Inspiron 15',
 'Asus ROG STRIX...',
 'Acer Nitro 5 A...',
 'Asus ROG STRIX...',
 'Lenovo ThinkPa...',
 'ThinkPad Yoga',
 'Lenovo ThinkPa...',
 'Dell Inspiron...',
 'MSI GL72M 7RDX',
 'MSI GL72M 7RDX',
 'Asus ROG Strix...',
 'Dell Latitude...',
 'Dell Latitude...',
 'Lenovo Legion...',
 'Toshiba Porteg...',
 'Acer Predator...',
 'Acer Aspire 7...',
 'Dell Inspiron...',
 'Dell Latitude...',
 'Lenovo Legion...',
 'Asus AsusPro A...',
 'Acer Nitro 5 A...',
 'Dell Latitude...',
 'Dell Inspiron...',
 'Dell Latitude...',
 'Lenovo Legion...',
 'MSI GP62M 7RDX...',
 'Lenovo Yoga 72...',
 'Toshiba Porteg...',
 'Acer TravelMat...',
 'Dell Latitude...',
 'ThinkPad T540p',
 'MSI GS63 7RD S...',
 'Dell Latitude...',
 'Acer Predator...',
 'MSI GL62M 7REX',
 'MSI GL62M 7REX...',
 'Lenovo Yoga 91...',
 'Toshiba Porteg...',
 'Lenovo IdeaPad...',
 'Acer Predator...',
 'ThinkPad Yoga',
 'Asus VivoBook...',
 'Dell Latitude...',
 'Asus ZenBook U...',
 'ThinkPad X230',
 'Asus ROG Strix...',
 'Apple MacBook...',
 'Dell Latitude...',
 'Hewlett Packar...',
 'Dell XPS 13',
 'Toshiba Porteg...',
 'MSI GL62VR 7RF...',
 'Dell Latitude...',
 'ThinkPad X240',
 'Hewlett Packar...',
 'Apple MacBook...',
 'Dell Latitude...',
 'Dell Latitude...',
 'Dell Latitude...',
 'Apple MacBook...',
 'Lenovo ThinkPa...',
 'Lenovo ThinkPa...',
 'Toshiba Porteg...',
 'Asus ASUSPRO B...',
 'Lenovo Legion...',
 'Asus ROG Strix...',
 'Asus ROG Strix...',
 'Asus ROG Strix...',
 'Asus ROG Strix...']

In [16]:
prices = soup.find_all("h4", class_="price")
pr = []
for price in prices:
  print(price.text.strip())
  pr.append(price.text.strip())

$295.99
$299
$299
$306.99
$321.94
$356.49
$364.46
$372.7
$379.94
$379.95
$391.48
$393.88
$399
$399.99
$404.23
$408.98
$409.63
$410.46
$410.66
$416.99
$433.3
$436.29
$436.29
$439.73
$454.62
$454.73
$457.38
$465.95
$468.56
$469.1
$484.23
$485.9
$487.8
$488.64
$488.78
$494.71
$497.17
$498.23
$520.99
$564.98
$577.99
$581.99
$609.99
$679
$679
$729
$739.99
$745.99
$799
$809
$899
$999
$1033.99
$1096.02
$1098.42
$1099
$1099
$1101.83
$1102.66
$1110.14
$1112.91
$1114.55
$1123.87
$1123.87
$1124.2
$1133.82
$1133.91
$1139.54
$1140.62
$1143.4
$1144.2
$1144.4
$1149
$1149
$1149.73
$1154.04
$1170.1
$1178.19
$1178.99
$1179
$1187.88
$1187.98
$1199
$1199
$1199.73
$1203.41
$1212.16
$1221.58
$1223.99
$1235.49
$1238.37
$1239.2
$1244.99
$1259
$1260.13
$1271.06
$1273.11
$1281.99
$1294.74
$1299
$1310.39
$1311.99
$1326.83
$1333
$1337.28
$1338.37
$1341.22
$1347.78
$1349.23
$1362.24
$1366.32
$1381.13
$1399
$1399
$1769
$1769
$1799

In [17]:
pr

['$295.99',
 '$299',
 '$299',
 '$306.99',
 '$321.94',
 '$356.49',
 '$364.46',
 '$372.7',
 '$379.94',
 '$379.95',
 '$391.48',
 '$393.88',
 '$399',
 '$399.99',
 '$404.23',
 '$408.98',
 '$409.63',
 '$410.46',
 '$410.66',
 '$416.99',
 '$433.3',
 '$436.29',
 '$436.29',
 '$439.73',
 '$454.62',
 '$454.73',
 '$457.38',
 '$465.95',
 '$468.56',
 '$469.1',
 '$484.23',
 '$485.9',
 '$487.8',
 '$488.64',
 '$488.78',
 '$494.71',
 '$497.17',
 '$498.23',
 '$520.99',
 '$564.98',
 '$577.99',
 '$581.99',
 '$609.99',
 '$679',
 '$679',
 '$729',
 '$739.99',
 '$745.99',
 '$799',
 '$809',
 '$899',
 '$999',
 '$1033.99',
 '$1096.02',
 '$1098.42',
 '$1099',
 '$1099',
 '$1101.83',
 '$1102.66',
 '$1110.14',
 '$1112.91',
 '$1114.55',
 '$1123.87',
 '$1123.87',
 '$1124.2',
 '$1133.82',
 '$1133.91',
 '$1139.54',
 '$1140.62',
 '$1143.4',
 '$1144.2',
 '$1144.4',
 '$1149',
 '$1149',
 '$1149.73',
 '$1154.04',
 '$1170.1',
 '$1178.19',
 '$1178.99',
 '$1179',
 '$1187.88',
 '$1187.98',
 '$1199',
 '$1199',
 '$1199.73',
 '$1203.41',
 '$1212.16',
 '$1221.58',
 '$1223.99',
 '$1235.49',
 '$1238.37',
 '$1239.2',
 '$1244.99',
 '$1259',
 '$1260.13',
 '$1271.06',
 '$1273.11',
 '$1281.99',
 '$1294.74',
 '$1299',
 '$1310.39',
 '$1311.99',
 '$1326.83',
 '$1333',
 '$1337.28',
 '$1338.37',
 '$1341.22',
 '$1347.78',
 '$1349.23',
 '$1362.24',
 '$1366.32',
 '$1381.13',
 '$1399',
 '$1399',
 '$1769',
 '$1769',
 '$1799']

In [18]:
descriptions = soup.find_all("p", class_="description")
desc = []
for description in descriptions:
  print(description.text.strip())
  desc.append(description.text.strip())

Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd
Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux
Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home
Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd
Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS
Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home
Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG
Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux
Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home
Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux
Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home
Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd
Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home
Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home
Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home
Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home
Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd
15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1
Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd
Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home
Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home
Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux
Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux
Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro
Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG
Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS
Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd
Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home
Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home
Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux
Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home
Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home
Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux
Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home
Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux
Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro
15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1
Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home
15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows
15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1
15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1
Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG
Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux
Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd
14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit
Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,
Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS
Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home
Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home
Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro
12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,
Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro
Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home
MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home
Asus ROG Strix GL553VD-DM535T, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home, Eng kbd
Apple MacBook Air 13.3", Core i5 1.8GHz, 8GB, 128GB SSD, Intel HD 4000, RUS
Dell Latitude 5280, 12.5" HD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro
Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Linux + Windows 10 Home
Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IPS, Core i5-7300HQ, 8 GB, 128GB SSD + 2 TB HDD, NVIDIA GeForce GTX 1060 6 GB, FreeDOS + Windows 10 Home
Toshiba Portege Z30-C-16J Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, Windows 10 Pro
Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050Ti 4GB, Windows 10 Home
Acer Aspire 7 A715-71G, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB HDD, GTX 1050 Ti 4GB, Windows 10 Home
Dell Inspiron 17 2in1 (7779) Silver, 17.3" FHD Touch, Core i5-7200U, 12GB, 1TB, GeForce GT940MX 2GB, Windows 10 Home
Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Windows 10 Pro
Lenovo Legion Y520, 15.6" FHD, Core i7-7700HQ, 8GB, 128 GB SSD + 1TB HDD, GTX 1050 4GB, Windows 10 Home
Asus AsusPro Advanced BU401LA-FA271G Dark Grey, 14", Core i5-4210U, 4GB, 128GB SSD, Win7 Pro 64bit, ENG
Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD +1TB, GeForce GTX 1050 Ti 4GB, Windows 10 Home + Windows 10 Home
Dell Latitude 5480, 14" FHD, Core i5-7440HQ, 8GB, 256GB SSD, Windows 10 Pro
Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB, GeForce GTX 1050 Ti 4GB, Linux + Windows 10 Home
Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro
Lenovo Legion Y520-15IKBM, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB, GeForce GTX 1060 Max-Q 6GB, DOS
MSI GP62M 7RDX Leopard, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home
Lenovo Yoga 720 Grey, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, Windows 10 Home
Toshiba Portege Z30-C-16L Grey, 13.3" FHD, Core i7-6500U, 8GB, 256GB SSD, Windows 10 Pro
Acer TravelMate P645-S-511A Black, 14" FHD IPS, Core i5-5200U, 8GB, 256GB SSD, 3G, Windows 10 Pro
Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 16GB, 256GB SSD, Linux + Windows 10 Home
15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit
MSI GS63 7RD Stealth, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, DOS + Windows 10 Home
Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro
Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ. 8GB, 128GB SSD +1TB, GeForce GTX 1050Ti 4GB, Linux + Windows 10 Home
MSI GL62M 7REX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home
MSI GL62M 7REX2, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home
Lenovo Yoga 910 Grey, 13.9" FHD Touch, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home
Toshiba Portege X30-D-10J Black/Blue, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro
Lenovo IdeaPad Miix 510 Platinum Silver, 12.2" IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro
Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home
12.5" Touch, Core i5 4200U, 8GB, 500GB + 16GB SSD Cache, Windows
Asus VivoBook Pro 15 N580VN-FI006T Gold Metal, 15.6" UHD, Core i7-7700HQ, 16GB, 1TB + 256GB SSD, GeForce MX150 2GB, Windows 10 Home, Eng kbd
Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux
Asus ZenBook UX530UX-FY040T Blue, 15.6" FHD, Core i7-7500U, 8GB, 512GB SSD, GeForce GTX950M 2GB, Windows 10 Home, Eng kbd
12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit
Asus ROG Strix GL753VE-GC096T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home, Eng kbd
Apple MacBook Air 13", i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, ENG
Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 1TB, GeForce GT930MX, Windows 10 Pro
Hewlett Packard Spectre 13-v106na Dark Ash Silver, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home
13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1
Toshiba Portege Z30-C-16K Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, 4G, Windows 10 Pro
MSI GL62VR 7RFX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 256GB SSD, GeForce GTX 1060 3GB, Windows 10 Home
Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro
12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit
Hewlett Packard ProBook 640 G3, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro
Apple MacBook Pro 13" Space Gray, Core i5 2.3GHz, 8GB, 128GB SSD, Iris Plus 640, ENG
Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 8GB, 256GB SSD, GeForce GT930MX, Windows 10 Pro
Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux + Windows 10 Home
Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 16GB, 256GB SSD, GeForce GT930MX, Linux
Apple MacBook Air 13", Intel Core i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, RUS
Lenovo ThinkPad T470, 14" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro
Lenovo ThinkPad Yoga 370 Black, 13.3" FHD IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro
Toshiba Portege X20W-D-10V Black/Blue, 12.5" FHD Touch, Core i7-7500U, 8GB, 512GB SSD, Windows 10 Pro
Asus ASUSPRO B9440UA-GV0279R Gray, 14" FHD, Core i7-7500U, 16GB, 512GB SSD, Windows 10 Pro, Eng kbd
Lenovo Legion Y720, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 2TB HDD, GeForce GTX 1060 6GB, DOS, RGB backlit keyboard
Asus ROG Strix GL702VM-GC146T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1060 3GB, Windows 10 Home, Eng kbd
Asus ROG Strix GL702ZC-GC154T, 17.3" FHD, Ryzen 7 1700, 16GB, 256GB + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home
Asus ROG Strix GL702ZC-GC209T, 17.3" FHD IPS, Ryzen 7 1700, 16GB, 256GB SSD + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home
Asus ROG Strix SCAR Edition GL503VM-ED115T, 15.6" FHD 120Hz, Core i7-7700HQ, 16GB, 256GB SSD + 1TB SSHD, GeForce GTX 1060 6GB, Windows 10 Home

In [19]:
desc

['Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
 '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
 'Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
 'Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home',
 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home',
 'Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home',
 'Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
 '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
 'Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd',
 'Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home',
 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home',
 'Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro',
 'Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG',
 'Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS',
 'Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd',
 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
 'Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux',
 'Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
 'Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home',
 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
 'Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home',
 'Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux',
 'Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro',
 '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
 '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
 '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
 '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
 '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
 '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
 'Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro',
 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home',
 'MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
 'Asus ROG Strix GL553VD-DM535T, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home, Eng kbd',
 'Apple MacBook Air 13.3", Core i5 1.8GHz, 8GB, 128GB SSD, Intel HD 4000, RUS',
 'Dell Latitude 5280, 12.5" HD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Linux + Windows 10 Home',
 'Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IPS, Core i5-7300HQ, 8 GB, 128GB SSD + 2 TB HDD, NVIDIA GeForce GTX 1060 6 GB, FreeDOS + Windows 10 Home',
 'Toshiba Portege Z30-C-16J Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, Windows 10 Pro',
 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050Ti 4GB, Windows 10 Home',
 'Acer Aspire 7 A715-71G, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB HDD, GTX 1050 Ti 4GB, Windows 10 Home',
 'Dell Inspiron 17 2in1 (7779) Silver, 17.3" FHD Touch, Core i5-7200U, 12GB, 1TB, GeForce GT940MX 2GB, Windows 10 Home',
 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Windows 10 Pro',
 'Lenovo Legion Y520, 15.6" FHD, Core i7-7700HQ, 8GB, 128 GB SSD + 1TB HDD, GTX 1050 4GB, Windows 10 Home',
 'Asus AsusPro Advanced BU401LA-FA271G Dark Grey, 14", Core i5-4210U, 4GB, 128GB SSD, Win7 Pro 64bit, ENG',
 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD +1TB, GeForce GTX 1050 Ti 4GB, Windows 10 Home + Windows 10 Home',
 'Dell Latitude 5480, 14" FHD, Core i5-7440HQ, 8GB, 256GB SSD, Windows 10 Pro',
 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB, GeForce GTX 1050 Ti 4GB, Linux + Windows 10 Home',
 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
 'Lenovo Legion Y520-15IKBM, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB, GeForce GTX 1060 Max-Q 6GB, DOS',
 'MSI GP62M 7RDX Leopard, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
 'Lenovo Yoga 720 Grey, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
 'Toshiba Portege Z30-C-16L Grey, 13.3" FHD, Core i7-6500U, 8GB, 256GB SSD, Windows 10 Pro',
 'Acer TravelMate P645-S-511A Black, 14" FHD IPS, Core i5-5200U, 8GB, 256GB SSD, 3G, Windows 10 Pro',
 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 16GB, 256GB SSD, Linux + Windows 10 Home',
 '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
 'MSI GS63 7RD Stealth, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, DOS + Windows 10 Home',
 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ. 8GB, 128GB SSD +1TB, GeForce GTX 1050Ti 4GB, Linux + Windows 10 Home',
 'MSI GL62M 7REX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
 'MSI GL62M 7REX2, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
 'Lenovo Yoga 910 Grey, 13.9" FHD Touch, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
 'Toshiba Portege X30-D-10J Black/Blue, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
 'Lenovo IdeaPad Miix 510 Platinum Silver, 12.2" IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home',
 '12.5" Touch, Core i5 4200U, 8GB, 500GB + 16GB SSD Cache, Windows',
 'Asus VivoBook Pro 15 N580VN-FI006T Gold Metal, 15.6" UHD, Core i7-7700HQ, 16GB, 1TB + 256GB SSD, GeForce MX150 2GB, Windows 10 Home, Eng kbd',
 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux',
 'Asus ZenBook UX530UX-FY040T Blue, 15.6" FHD, Core i7-7500U, 8GB, 512GB SSD, GeForce GTX950M 2GB, Windows 10 Home, Eng kbd',
 '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit',
 'Asus ROG Strix GL753VE-GC096T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home, Eng kbd',
 'Apple MacBook Air 13", i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, ENG',
 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 1TB, GeForce GT930MX, Windows 10 Pro',
 'Hewlett Packard Spectre 13-v106na Dark Ash Silver, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
 '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1',
 'Toshiba Portege Z30-C-16K Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
 'MSI GL62VR 7RFX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 256GB SSD, GeForce GTX 1060 3GB, Windows 10 Home',
 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
 '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit',
 'Hewlett Packard ProBook 640 G3, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
 'Apple MacBook Pro 13" Space Gray, Core i5 2.3GHz, 8GB, 128GB SSD, Iris Plus 640, ENG',
 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 8GB, 256GB SSD, GeForce GT930MX, Windows 10 Pro',
 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux + Windows 10 Home',
 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 16GB, 256GB SSD, GeForce GT930MX, Linux',
 'Apple MacBook Air 13", Intel Core i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, RUS',
 'Lenovo ThinkPad T470, 14" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
 'Lenovo ThinkPad Yoga 370 Black, 13.3" FHD IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
 'Toshiba Portege X20W-D-10V Black/Blue, 12.5" FHD Touch, Core i7-7500U, 8GB, 512GB SSD, Windows 10 Pro',
 'Asus ASUSPRO B9440UA-GV0279R Gray, 14" FHD, Core i7-7500U, 16GB, 512GB SSD, Windows 10 Pro, Eng kbd',
 'Lenovo Legion Y720, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 2TB HDD, GeForce GTX 1060 6GB, DOS, RGB backlit keyboard',
 'Asus ROG Strix GL702VM-GC146T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1060 3GB, Windows 10 Home, Eng kbd',
 'Asus ROG Strix GL702ZC-GC154T, 17.3" FHD, Ryzen 7 1700, 16GB, 256GB + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
 'Asus ROG Strix GL702ZC-GC209T, 17.3" FHD IPS, Ryzen 7 1700, 16GB, 256GB SSD + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
 'Asus ROG Strix SCAR Edition GL503VM-ED115T, 15.6" FHD 120Hz, Core i7-7700HQ, 16GB, 256GB SSD + 1TB SSHD, GeForce GTX 1060 6GB, Windows 10 Home']

In [20]:

ratings = soup.find_all("p",{'data-rating': True})
rate = []
for i in ratings:
  r = i.get("data-rating")
  rate.append(r)
  print(r)

3
2
4
3
3
2
1
2
2
4
4
3
1
4
1
4
3
4
4
2
1
1
1
4
1
2
3
1
3
3
3
3
2
3
4
4
1
3
2
2
2
1
1
2
2
1
4
3
2
1
1
3
2
4
1
4
1
2
1
3
4
1
2
2
3
4
1
3
3
4
1
3
3
1
2
1
1
3
1
1
3
3
1
2
3
4
4
1
3
2
2
1
3
4
4
1
3
3
1
3
3
3
1
1
1
2
3
2
1
2
1
1
3
3
4
1
3

In [21]:
rate

['3',
 '2',
 '4',
 '3',
 '3',
 '2',
 '1',
 '2',
 '2',
 '4',
 '4',
 '3',
 '1',
 '4',
 '1',
 '4',
 '3',
 '4',
 '4',
 '2',
 '1',
 '1',
 '1',
 '4',
 '1',
 '2',
 '3',
 '1',
 '3',
 '3',
 '3',
 '3',
 '2',
 '3',
 '4',
 '4',
 '1',
 '3',
 '2',
 '2',
 '2',
 '1',
 '1',
 '2',
 '2',
 '1',
 '4',
 '3',
 '2',
 '1',
 '1',
 '3',
 '2',
 '4',
 '1',
 '4',
 '1',
 '2',
 '1',
 '3',
 '4',
 '1',
 '2',
 '2',
 '3',
 '4',
 '1',
 '3',
 '3',
 '4',
 '1',
 '3',
 '3',
 '1',
 '2',
 '1',
 '1',
 '3',
 '1',
 '1',
 '3',
 '3',
 '1',
 '2',
 '3',
 '4',
 '4',
 '1',
 '3',
 '2',
 '2',
 '1',
 '3',
 '4',
 '4',
 '1',
 '3',
 '3',
 '1',
 '3',
 '3',
 '3',
 '1',
 '1',
 '1',
 '2',
 '3',
 '2',
 '1',
 '2',
 '1',
 '1',
 '3',
 '3',
 '4',
 '1',
 '3']

In [22]:
reviews = soup.find_all("span",{"itemprop":"reviewCount"})
review = []
for i in reviews:
  review.append(i.text.strip())
  print(i.text)

14
8
12
2
5
6
12
2
0
9
10
9
4
3
12
10
9
14
4
2
1
1
2
6
9
2
9
7
1
5
8
6
9
4
14
2
9
5
13
0
10
2
4
9
7
2
8
12
7
0
7
11
13
14
7
1
9
4
8
4
1
0
1
4
10
14
13
7
14
5
2
10
11
11
12
7
0
6
2
2
5
14
7
12
7
13
0
9
2
10
0
14
10
7
8
13
8
4
6
1
8
12
2
0
6
11
3
11
5
12
11
4
8
10
7
8
8

In [23]:
review

['14',
 '8',
 '12',
 '2',
 '5',
 '6',
 '12',
 '2',
 '0',
 '9',
 '10',
 '9',
 '4',
 '3',
 '12',
 '10',
 '9',
 '14',
 '4',
 '2',
 '1',
 '1',
 '2',
 '6',
 '9',
 '2',
 '9',
 '7',
 '1',
 '5',
 '8',
 '6',
 '9',
 '4',
 '14',
 '2',
 '9',
 '5',
 '13',
 '0',
 '10',
 '2',
 '4',
 '9',
 '7',
 '2',
 '8',
 '12',
 '7',
 '0',
 '7',
 '11',
 '13',
 '14',
 '7',
 '1',
 '9',
 '4',
 '8',
 '4',
 '1',
 '0',
 '1',
 '4',
 '10',
 '14',
 '13',
 '7',
 '14',
 '5',
 '2',
 '10',
 '11',
 '11',
 '12',
 '7',
 '0',
 '6',
 '2',
 '2',
 '5',
 '14',
 '7',
 '12',
 '7',
 '13',
 '0',
 '9',
 '2',
 '10',
 '0',
 '14',
 '10',
 '7',
 '8',
 '13',
 '8',
 '4',
 '6',
 '1',
 '8',
 '12',
 '2',
 '0',
 '6',
 '11',
 '3',
 '11',
 '5',
 '12',
 '11',
 '4',
 '8',
 '10',
 '7',
 '8',
 '8']

In [24]:
images = soup.find_all("img", class_="img-fluid")
image_links = []
for image in images:
    print(image.get("src"))
    image_links.append(image.get("src"))

/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png
/images/test-sites/e-commerce/items/cart2.png

In [25]:
image_links

['/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png',
 '/images/test-sites/e-commerce/items/cart2.png']

In [26]:
data = {
    "Name":na,
    "Description":desc,
    "Rating":rate,
    "Reviews":review,
    "Images Links":image_links
}

In [27]:
import pandas as pd

In [28]:
df = pd.DataFrame(data)
df.head()

,Name,Description,Rating,Reviews,Images Links
0,Asus VivoBook...,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",3,14,/images/test-sites/e-commerce/items/cart2.png
1,Prestigio Smar...,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",2,8,/images/test-sites/e-commerce/items/cart2.png
2,Prestigio Smar...,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",4,12,/images/test-sites/e-commerce/items/cart2.png
3,Aspire E1-510,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",3,2,/images/test-sites/e-commerce/items/cart2.png
4,Lenovo V110-15...,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",3,5,/images/test-sites/e-commerce/items/cart2.png

In [29]:
df.iloc[0,0] = "Ujjwal Neupane"
df.head()

,Name,Description,Rating,Reviews,Images Links
0,Ujjwal Neupane,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",3,14,/images/test-sites/e-commerce/items/cart2.png
1,Prestigio Smar...,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",2,8,/images/test-sites/e-commerce/items/cart2.png
2,Prestigio Smar...,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",4,12,/images/test-sites/e-commerce/items/cart2.png
3,Aspire E1-510,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",3,2,/images/test-sites/e-commerce/items/cart2.png
4,Lenovo V110-15...,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",3,5,/images/test-sites/e-commerce/items/cart2.png

In [30]:
# loc

df.set_index("Name", inplace=True)
df.head()

,Description,Rating,Reviews,Images Links
Name,,,,
Ujjwal Neupane,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",3,14,/images/test-sites/e-commerce/items/cart2.png
Prestigio Smar...,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",2,8,/images/test-sites/e-commerce/items/cart2.png
Prestigio Smar...,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",4,12,/images/test-sites/e-commerce/items/cart2.png
Aspire E1-510,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",3,2,/images/test-sites/e-commerce/items/cart2.png
Lenovo V110-15...,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",3,5,/images/test-sites/e-commerce/items/cart2.png

In [32]:
df.to_csv("Ecommerce.csv")